[versions]
kotlin = "2.2.21"
ktor = "3.3.3"

[libraries]
common-ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
common-ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
common-ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
common-ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

common-result = "com.ioki.result:result:0.3.0"

common-test-kotlin = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
common-test-ktorMock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
common-test-kotest = "io.kotest:kotest-assertions-core:6.0.7"

jvm-ktor-client = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
jvm-ktor-logging = "ch.qos.logback:logback-classic:1.5.21"

macos-ktor-client = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

linux-ktor-client = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }

mingw-ktor-client = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinDokka = "org.jetbrains.dokka:2.1.0"
nmcp = "com.gradleup.nmcp:1.3.0"
ktlint = "org.jlleitschuh.gradle.ktlint:14.0.1"
