[versions]
kotlin = "1.9.20"
ktor = "2.3.6"

[libraries]
common-ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
common-ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
common-ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
common-ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

common-test-kotlin = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
common-test-ktorMock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

jvm-ktor-client = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
jvm-ktor-logging = "ch.qos.logback:logback-classic:1.4.12"

macos-ktor-client = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

linux-ktor-client = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }

mingw-ktor-client = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinDokka = "org.jetbrains.dokka:1.9.10"